name 'test_services'
maintainer 'Bryan Wann'
maintainer_email 'bwann-chef@wann.net'
license 'Apache-2.0'
description 'Includes all cookbooks under CI for Test Kitchen purposes'
source_url 'https://github.com/bwann/chef'
# never EVER change this number, ever.
version '0.0.1'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'ubuntu'
depends 'fb_helpers'
depends 'fb_systemd'
depends 'fb_users'
depends 'wn_exabgp'
depends 'wn_kea'
depends 'wn_mgetty'
depends 'wn_squid'
# vim: syntax=ruby:expandtab:shiftwidth=2:softtabstop=2:tabstop=2
