# vim: syntax=ruby:expandtab:shiftwidth=2:softtabstop=2:tabstop=2
name 'wn_exabgp'
maintainer 'Bryan Wann'
maintainer_email 'bwann-chef@wann.net'
license 'Apache-2.0'
description 'Installs/Configures ExaBGP'
source_url 'https://github.com/bwann/chef'
# never EVER change this number, ever.
version '0.1.0'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'ubuntu'
depends 'fb_helpers'
depends 'fb_users'
